### ISSUE TITLE
Praktikumsseite Design 

### ISSUE THREAD

**Issue by EggiEl** [EggiEl/TryGain#4]
Beitrag erstellen Elias
Design Hannah

**Comment by hannahsophiegr** [comment]
ich hab des Design davon gemacht, kannst du mal drüber schauen, ist aber relativ ähnlich gehalten zu den Mockups und den Studiengängen, um die Konsistenz zu behalten

**Comment by hannahsophiegr** [comment]
fertig, haben ja noch kein konzept für entwickelt was genau passiert, wenn man auf bewerben geht etc.
